### ISSUE TITLE
AttributeError: 'HigherOrderOperator' object has no attribute 'py_functionalize_impl'

### ISSUE THREAD

**Issue by ice-ux** [pytorch/executorch#1413] opened 2023-12-14 04:10 UTC
Traceback (most recent call last):
  File "C:\Users\17255\.conda\envs\myenv\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\17255\.conda\envs\myenv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\edge\executorch\examples\xnnpack\aot_compiler.py", line 14, in <module>
    from executorch.backends.xnnpack.partition.xnnpack_partitioner import XnnpackPartitioner
  File "C:\Users\17255\.conda\envs\myenv\lib\site-packages\executorch\backends\xnnpack\__init__.py", line 8, in <module>   
    from .partition.xnnpack_partitioner import (
  File "C:\Users\17255\.conda\envs\myenv\lib\site-packages\executorch\backends\xnnpack\partition\xnnpack_partitioner.py", l
ine 14, in <module>
    from executorch.backends.xnnpack.partition.configs import (
  File "C:\Users17255\.conda\envs\myenv\lib\site-packages\executorch\backends\xnnpack\partition\configs.py", line 8, in <m
odule>
    from executorch.exir.dialects._ops import ops as exir_ops
  File "C:\Users\17255\.conda\envs\myenv\lib\site-packages\executorch\exir\__init__.py", line 9, in <module>
    from executorch.exir.capture import (
  File "C:\Users\17255\.conda\envs\myenv\lib\site-packages\executorch\exir\passes\__init__.py", line 19, in <module>       
    from executorch.exir import control_flow, memory, memory_planning
  File "C:\Users\17255\.conda\envs\myenv\lib\site-packages\executorch\exir\memory_planning.py", line 20, in <module>       
    from executorch.exir.delegate import executorch_call_delegate
  File "C:\Users\17255\.conda\envs\myenv\lib\site-packages\executorch\exir\delegate.py", line 120, in <module>
    @executorch_call_delegate.py_functionalize_impl
AttributeError: 'HigherOrderOperator' object has no attribute 'py_functionalize_impl'

**Comment by kegsay** [comment] 2023-12-14 14:52
I'm also getting this on MacOS when trying to follow the tutorial https://pytorch.org/executorch/stable/getting-started-setup.html#generate-a-sample-executorch-program - `AttributeError: 'HigherOrderOperator' object has no attribute 'py_functionalize_impl'`

When running: `python3 -m examples.portable.scripts.export --model_name="add"`

**Comment by kegsay** [comment] 2023-12-14 14:56
I'm guessing this is due to https://github.com/pytorch/executorch/pull/1149 which is weird as the tutorial specifically pins to branch v0.1.0 from October, whereas that PR is from November.

**Comment by mergennachin** [comment] 2023-12-14 16:45
Hi @huydhn 

For `release/0.1` branch, we use a specific torch nightly version dev20231010. However, looks like it is expired recently. Is it possible to keep the binary permanently?

https://github.com/pytorch/executorch/blob/release/0.1/install_requirements.sh

https://download.pytorch.org/whl/nightly/torch/

**Comment by huydhn** [comment] 2023-12-14 19:41
So, dev20231010 nightly binaries are still there, but it's now older than 60 days and has been removed from PyTorch nightly index.  After chatting with @mergennachin a bit, we have decided on the following steps:

* https://github.com/pytorch/builder/pull/1642 is a quick fix to keep dev20231010 in the nightly index.  It has been committed and the index re-generated.  So, the issue is mitigated now, and I can run `bash install_requirements.sh` locally without any issue
```
$ conda list | grep torch
executorch                0.1.0                    pypi_0    pypi
pytorch-pkg-helpers       0.1.5                    pypi_0    pypi
torch                     2.2.0.dev20231010          pypi_0    pypi
torchaudio                2.2.0.dev20231010          pypi_0    pypi
torchfix                  0.1.1                    pypi_0    pypi
torchsr                   1.0.4                    pypi_0    pypi
torchvision               0.17.0.dev20231010          pypi_0    pypi
```
* In ExecuTorch future releases, we need to use PyTorch stable releases instead (and test against them too).  PyTorch stable release schedule for 2024 can be found here https://dev-discuss.pytorch.org/t/release-cadence-for-year-2023-2024/1557

**Comment by mergennachin** [comment] 2023-12-14 23:58
Thank you, @huydhn

**Closed by mergennachin** 2023-12-14 23:58 UTC
Labels: bug, actionable, module: ci, high priority, triaged

**Comment by AlexRibard** [comment] 2024-01-20 19:48
I'm still getting the issue, even when using dev20231010 for torch version

**Comment by AlexRibard** [comment] 2024-01-20 20:00
when using torch.2.3.0.dev20240120+cpu I'm getting another error 
```TypeError: HigherOrderOperator.__init__() got an unexpected keyword argument '_deprecated_global_ns'``

**Comment by AlexRibard** [comment] 2024-01-20 20:19
fyi trying to run
https://pytorch.org/executorch/stable/ir-exir.html
