### ISSUE TITLE
AttributeError: 'HigherOrderOperator' object has no attribute 'py_functionalize_impl'

### ISSUE THREAD

**Issue by AlexRibard** [pytorch/executorch#1663] opened 2024-01-21 01:50 UTC
I've followed the steps outlined https://pytorch.org/executorch/stable/getting-started-setup.html
But after running
```
python3 -m examples.portable.scripts.export --model_name="add"
```
I am getting the following error
```
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.8/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/home/azureuser/executorch/examples/portable/__init__.py", line 7, in <module>
    from .utils import export_to_edge, export_to_exec_prog, save_pte_program
  File "/home/azureuser/executorch/examples/portable/utils.py", line 11, in <module>
    import executorch.exir as exir
  File "/home/azureuser/executorch/.executorch/lib/python3.8/site-packages/executorch/exir/__init__.py", line 9, in <module>
    from executorch.exir.capture import (
  File "/home/azureuser/executorch/.executorch/lib/python3.8/site-packages/executorch/exir/capture/__init__.py", line 9, in <module>
    from executorch.exir.capture._capture import (
  File "/home/azureuser/executorch/.executorch/lib/python3.8/site-packages/executorch/exir/capture/_capture.py", line 14, in <module>
    from executorch.exir.capture._config import CaptureConfig
  File "/home/azureuser/executorch/.executorch/lib/python3.8/site-packages/executorch/exir/capture/_config.py", line 12, in <module>
    from executorch.exir.passes import MemoryPlanningPass, ToOutVarPass
  File "/home/azureuser/executorch/.executorch/lib/python3.8/site-packages/executorch/exir/passes/__init__.py", line 19, in <module>
    from executorch.exir import control_flow, memory, memory_planning
  File "/home/azureuser/executorch/.executorch/lib/python3.8/site-packages/executorch/exir/memory_planning.py", line 20, in <module>
    from executorch.exir.delegate import executorch_call_delegate
  File "/home/azureuser/executorch/.executorch/lib/python3.8/site-packages/executorch/exir/delegate.py", line 122, in <module>
    @executorch_call_delegate.py_functionalize_impl
AttributeError: 'HigherOrderOperator' object has no attribute 'py_functionalize_impl'
```

**Comment by huydhn** [comment] 2024-01-22 17:36
Let me take a look, the files are still there on S3, but they are gone from the index.  The code was moved around recently in https://github.com/pytorch/test-infra/pull/4879, so may be it causes a regression

**Comment by huydhn** [comment] 2024-01-22 18:04
This should be fixed by https://github.com/pytorch/test-infra/pull/4900

**Comment by AlexRibard** [comment] 2024-01-22 18:04
Duplicate of https://github.com/pytorch/executorch/issues/1662 I'd say. 
With conda all is good. It's really pip which messes up dependencies

**Comment by huydhn** [comment] 2024-01-22 18:19
The files are back in the index now https://download.pytorch.org/whl/nightly/torch/ and `pip install --force-reinstall --pre torch=="2.2.0.dev20231010" -i https://download.pytorch.org/whl/nightly/cpu` works as expected.

**Comment by mergennachin** [comment] 2024-01-22 18:35
Thanks @huydhn 

I just went through the setup script in https://pytorch.org/executorch/stable/getting-started-setup.html from beginning to end.

Works for me now.

Thanks @AlexRibard  for reporting. This was an actual bug on our side where torch=="2.2.0.dev20231010" (that stable branch, v0.1.0, uses) doesn't exist in the nightly index. Huy just updated it.

**Closed by mergennachin** 2024-01-22 18:35 UTC
Labels: bug, module: ci, high priority, triaged
