### ISSUE TITLE
buck2 build failure

### ISSUE THREAD

**Issue by adonnini** [pytorch/executorch#2198] opened 2024-03-01 14:55 UTC
Hi,
I did the following:
1) ```rm /tmp/buck2```
2) Stopped execution of processes ```buck2``` and ```buck2[executorch]```
3) Downloaded latest ```buck2``` release ```buck2-x86_64-unknown-linux-musl.zst``` from https://github.com/facebook/buck2/releases/tag/latest
4) Ran ```zstd -cdq /home/adonnini1/Downloads/buck2-x86_64-unknown-linux-musl.zst  > /tmp/buck2 && chmod +x /tmp/buck2```   It completed successfully (i.e. no error message)
5) Ran ```/tmp/buck2 build //examples/portable/executor_runner:executor_runner --show-output```
It failed. Below, you will find the output.

All of the above were run in ```(executorch_with_3.1)``` conda environment in directory executorch

What did I do wrong?

Thanks

BUCK2 BUILD ERROR LOG
---------------------------------------
```
Could not connect to buck2 daemon (buck2 daemon is not running), starting a new one...
Connected to new buck2 daemon.
Build ID: 1d3d43fe-23a4-4fc4-94b1-272c52711a48
Jobs completed: 3. Time elapsed: 0.0s.
BUILD FAILED
From load at implicit location

Caused by:
    0: From load at third-party/prelude/prelude.bzl:8
    1: Error parsing: `prelude//native.bzl`
    2: error: list of 1 element expression is not allowed in type expression
          --> third-party/prelude/native.bzl:166:42
           |
       166 | def _get_valid_cpu_filters(cpu_filters: [[str], None]) -> [str]:
           |                                          ^^^^^
           |
       
```

**Comment by cccclai** [comment] 2024-03-06 03:59
The buck2 version is bumped. It should be resolved with the new buck2 from  https://github.com/facebook/buck2/releases/tag/2024-02-15

Let us know if the issue is still there

**Comment by adonnini** [comment] 2024-03-06 14:16
@cccclai Thanks. Unfortunately, the same error persists.
I tried using the buck2 release you pointed me to and the latest (https://github.com/facebook/buck2/releases/tag/latest)
I must be doing something wrong.
FYI, I have executorch installed in two different locations on my system. the buck2 build fails only in one (The last time I ran the buck2 build in the other location it worked).

**Comment by cccclai** [comment] 2024-03-06 20:12
> @cccclai Thanks. Unfortunately, the same error persists. I tried using the buck2 release you pointed me to and the latest (https://github.com/facebook/buck2/releases/tag/latest) I must be doing something wrong. FYI, I have executorch installed in two different locations on my system. the buck2 build fails only in one (I just I ran the buck2 build in the other location. It worked).

I feel like maybe it's related to the buck2 cache. Does it work if we do `buck clean` `buck kill`?

**Comment by adonnini** [comment] 2024-03-06 20:31
Good point. 
I ran the buck2 with the clean and kill options. executorch/buckout is empty
When I run the buck2 build unfortunately the result is the same.

Because the error involves ```prelude```, I ran ```pip install prelude``` to see what would happen. Below is the output. I wonder if this is related to the problem

PIP INSTALL PRELUDE OUTPUT
------------------------------------------------
```
SourceCode/NeuralNetworks/LocationPrediction/executorch$ pip install prelude
Collecting prelude
  Using cached prelude-5.1.1-1.tar.gz (81 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Discarding https://files.pythonhosted.org/packages/35/18/ebbdd6f4932f64d5a1c272d7c722227eeb9b49b0cfd3b441ebc28729041e/prelude-5.1.1-1.tar.gz (from https://pypi.org/simple/prelude/): Requested prelude from https://files.pythonhosted.org/packages/35/18/ebbdd6f4932f64d5a1c272d7c722227eeb9b49b0cfd3b441ebc28729041e/prelude-5.1.1-1.tar.gz has inconsistent version: expected '5.1.1.post1', but metadata has '5.1.1'
ERROR: Could not find a version that satisfies the requirement prelude (from versions: 5.1.1.post1)
ERROR: No matching distribution found for prelude
```

**Comment by adonnini** [comment] 2024-03-06 20:45
@cccclai It may not make sense for you to spend any more time for this since the buck2 build does work in one of my executorch installations and, please correct me if I am wrong, I do not need it in order to produce a lowered model to run on an Android device (right?).
Thanks for your help and responsiveness

**Comment by cccclai** [comment] 2024-03-07 01:05
Oh running `pip install prelude` directly might not work. It needs to be pinned to this commit https://github.com/facebook/buck2-prelude/tree/923237d9e55a8f5a0ad0eeb1154388e8f159f62f

**Comment by adonnini** [comment] 2024-03-09 21:31
@cccclai I completely re-installled/set up executorch for the model where this buck2 problem occurred. Everything works now. I think we might as well close this issue.
Thanks for your help

**Closed** 2024-03-15 23:50 UTC
