### ISSUE TITLE
Error with lowering ViT to QNN backend

### ISSUE THREAD

**Issue by kirklandsign** [pytorch/executorch#1182] opened 2023-11-09 17:33 UTC
Please use mobilenet_v2.py script to repro and replace `mv2` with `vit`. Then run the script. I skipped the adb model run part.

Got the following error:

```
[INFO][Qnn ExecuTorch] create QNN Logger with log_level 2
[WARNING]QnnDsp <W> Initializing HtpProvider

[INFO][Qnn ExecuTorch] Initialize Qnn backend parameters for Qnn executorch backend type 2
[INFO][Qnn ExecuTorch] Caching: Caching is in SAVE MODE.
[INFO][Qnn ExecuTorch] Running level=3 optimization.
[QNN Partitioner Op Support]: aten.convolution.default | True
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_2:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_2 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_3:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_3 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_6:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_6 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_7:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_7 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_10:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_10 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_11:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_11 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_14:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_14 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_15:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_15 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_18:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_18 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_19:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_19 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_22:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_22 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_23:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_23 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_26:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_26 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_27:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_27 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_30:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_30 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_31:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_31 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_34:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_34 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_35:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_35 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_38:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_38 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_39:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_39 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_42:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_42 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_43:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_43 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_46:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_46 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.view_copy.default | True
[ERROR]QnnDsp <E> validateNativeOps aten_linear_default_47:qti.aisw:FullyConnected op validator (quantized and FP16) failed 3110 and 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_linear_default_47 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.linear.default | False
[QNN Partitioner Op Support]: aten.linear.default | True
[QNN Partitioner Op Support]: aten.linear.default | True
[ERROR]Tensor 0 and 0 have mismatching datatypes. 0x408 != 0x232.

[ERROR]Op specific validation failed.

[ERROR]QnnDsp <E> validateNativeOps master op validator aten_select_copy_int_36:qti.aisw:StridedSlice failed 3110

[ERROR]QnnDsp <E> QnnBackend_validateOpConfig failed 3110

[ERROR]QnnDsp <E> Failed to validate op aten_select_copy_int_36 with error 0xc26

[WARNING][Qnn ExecuTorch] Qnn Backend op validation failed with error: 3110
[QNN Partitioner Op Support]: aten.select_copy.int | False
Traceback (most recent call last):
  File "/home/hsz/local/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/hsz/local/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/hsz/executorch/examples/qualcomm/scripts/vit.py", line 132, in <module>
    build_executorch_binary(
  File "/home/hsz/executorch/examples/qualcomm/scripts/utils.py", line 169, in build_executorch_binary
    edge_prog.exported_program = to_backend(edge_prog.exported_program, QnnPartitioner)
  File "/home/hsz/local/miniconda3/envs/executorch/lib/python3.10/functools.py", line 878, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/home/hsz/executorch/exir/backend/backend_api.py", line 296, in _
    partitioner_result = partitioner_instance(copied_edge_program)
  File "/home/hsz/executorch/exir/backend/partitioner.py", line 57, in __call__
    return self.partition(exported_program)
  File "/home/hsz/executorch/backends/qualcomm/partition/qnn_partitioner.py", line 127, in partition
    partitions = self.generate_partitions(graph_module)
  File "/home/hsz/executorch/backends/qualcomm/partition/qnn_partitioner.py", line 111, in generate_partitions
    return generate_partitions_from_list_of_nodes(
  File "/home/hsz/executorch/exir/backend/canonical_partitioners/pattern_op_partitioner.py", line 50, in generate_partitions_from_list_of_nodes
    partition_list = capability_partitioner.propose_partitions()
  File "/home/hsz/local/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/fx/passes/infra/partitioner.py", line 150, in propose_partitions
    if self.__is_node_supported(node) and node not in assignment:
  File "/home/hsz/local/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/fx/passes/infra/partitioner.py", line 55, in __is_node_supported
    self.operator_support.is_node_supported(dict(self.graph_module.named_modules()), node)
  File "/home/hsz/local/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/fx/passes/operator_support.py", line 145, in is_node_supported
    return is_node_supported(submodules, node)
  File "/home/hsz/local/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/fx/passes/operator_support.py", line 170, in _any_chain
    return any(
  File "/home/hsz/local/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/fx/passes/operator_support.py", line 171, in <genexpr>
    x.is_node_supported(submods, node)
  File "/home/hsz/executorch/backends/qualcomm/partition/qnn_partitioner.py", line 50, in is_node_supported
    op_wrapper = self.node_visitors[node.target.__name__].define_node(
KeyError: 'aten.native_layer_norm.default'
[INFO][Qnn ExecuTorch] Destroy Qnn context
[INFO][Qnn ExecuTorch] Destroy Qnn device
[INFO][Qnn ExecuTorch] Destroy Qnn backend

```

**Comment by chiwwang** [comment] 2023-11-10 02:46
@haowhsu-quic , let's plan and check this issue.

**Comment by haowhsu-quic** [comment] 2023-11-10 03:36
I think the breakage was caused by no QDQ pattern got inserted on parameter of `linear` after `convert_pt2e`, is this expected?

**Comment by haowhsu-quic** [comment] 2023-11-10 10:49
Thanks @shewu-quic help figure out the problem, he will soon provide a fix PR.

**Comment by kirklandsign** [comment] 2023-11-14 19:25
Thanks @haowhsu-quic @shewu-quic for your help!

For the first issue, is it on `QnnQuantizer` side, not on `convert_pt2e`?

**Comment by jerryzh168** [comment] 2023-11-15 01:00
> no QDQ pattern got inserted on parameter of linear after convert_pt2e

this should be configurable in the quantizer that you are using I think, see https://pytorch.org/tutorials/prototype/pt2e_quantizer.html for how to write a quantizer

**Comment by shewu-quic** [comment] 2023-11-15 01:12
@kirklandsign 
To my findings It seems that we need to make quantization annotation on linear node's weight and bias via
input_qspec_map
https://github.com/pytorch/executorch/blob/main/backends/qualcomm/qnn_quantizer.py#L519

**Comment by haowhsu-quic** [comment] 2023-11-15 01:27
> > no QDQ pattern got inserted on parameter of linear after convert_pt2e
> 
> this should be configurable in the quantizer that you are using I think, see https://pytorch.org/tutorials/prototype/pt2e_quantizer.html for how to write a quantizer

@jerryzh168 , thank you for the information. I think our annotation in quantizer might be too stale. After applying this API change regarding to [linear](https://github.com/pytorch/pytorch/commit/99168c1fa98d7acb69fd4ee43f22477de3674e06), things are working smoothly.
@kirklandsign , issue #1183 will be fixed first in this [PR](https://github.com/pytorch/executorch/pull/1043). Please also take a look, thank you!

**Comment by haowhsu-quic** [comment] 2023-12-04 16:34
I think inception_v3 should be ok now, we have tested it locally. Please have a look on this [PR](https://github.com/pytorch/executorch/pull/1293), which adds quantized ic3 example script.
For ViT, we might wait until quantization refactor [PR](https://github.com/pytorch/executorch/pull/1339) got merged, since ViT needs new annotation mechanism for enablement.

**Comment by haowhsu-quic** [comment] 2023-12-05 01:38
Thank you for the testing! Will work on it asap.

Yes, two issues are related, parts of them were introduced be PyTorch uplevel. For ViT, besides the missing operators, we also need new quantizer to tackle with `aten.scaled_dot_product_attention.default`.

**Comment by kirklandsign** [comment] 2023-12-14 19:13
Hi @haowhsu-quic may I friendly ask about the updates for this model?

**Comment by haowhsu-quic** [comment] 2023-12-15 02:13
ViT enablement is under review internally, will have PR in few days.

**Comment by shewu-quic** [comment] 2023-12-19 05:33
Hi all,
I create the PR https://github.com/pytorch/executorch/pull/1442 to enable quantized vit for QNN.
Could you please help to review?

Thanks,
Hutton

**Comment by mergennachin** [comment] 2024-05-13 17:49
Looks like fixed with https://github.com/pytorch/executorch/pull/1839

**Closed by mergennachin** 2024-05-13 17:49 UTC
Labels: partner: qualcomm, triaged
